export { CentrosPage } from './Centros.jsx'
export { ConvocatoriasPage } from './Convocatorias.jsx'
export { ConvocatoriasAddPage } from './ConvocatoriasAddPage.jsx'
export { CorreoPage } from './Correo.jsx'
export { LoginPage } from './Login.jsx'
export { PrincipalPage } from './Principal.jsx'
